# Generated by Django 6.1 on 2026-08-18 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
