# Generated by Django 6.1 on 2026-08-18 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_automovel_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovel',
            name='cor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='automovel',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
