# Generated by Django 6.0.5 on 2026-06-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_tag_contato_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
