# Generated by Django 6.0.5 on 2026-06-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_nome_contato_nome_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='nome_completo',
            new_name='nome',
        ),
    ]
